services:
  couchdb:
    image: couchdb:3.5.0
    container_name: couchdb
    restart: unless-stopped
    configs:
      - source: couchdb_single_node
        target: /opt/couchdb/etc/local.d/single-node.ini

    environment:
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

    ports:
      - "5984:5984"

    volumes:
      - type: bind
        source: ${COUCHDB_DATA}
        target: /opt/couchdb/data
        is_directory: true

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    labels:
      org.opencontainers.image.description: >-
        Apache CouchDB es una base de datos NoSQL orientada a documentos
        que almacena información en formato JSON y ofrece acceso mediante
        una API HTTP, replicación y sincronización distribuida.

configs:
  couchdb_single_node:
    content: |
      [couchdb]
      single_node = true