services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: "1000:1000"
    ports:
      - 8081:80/tcp
    volumes:
      - type: bind
        source:  ${FILEBROWSER_DATA}:/srv
        is_directory: true
      - type: bind
        source:  ${FILEBROWSER_DATABASE}:/database
        is_directory: true
      - type: bind
        source:  ${FILEBROWSER_CONFIG}:/config
        is_directory: true
    restart: 'unless-stopped'
    networks:
      - proxy

networks:
  proxy:
    external: true
