services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: "1000:1000"
    ports:
      - 8081:80/tcp
    volumes:
      - ${FILEBROWSER_DATA}:/srv
      - ${FILEBROWSER_DATABASE}:/database
      - ${FILEBROWSER_CONFIG}:/config
    restart: 'unless-stopped'
    networks:
      - proxy

networks:
  proxy:
    external: true