services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - type: bind
        source: ${JELLYFIN_CONFIG}
        target: /etc/jellyfin
        is_directory: true
      - type: bind
        source:  ${JELLYFIN_CACHE}
        target: /cache
        is_directory: true
      - type: bind
        source:  ${JELLYFIN_DATA}
        target: /var/lib/jellyfin
        is_directory: true
      - type: bind
        source:  ${MEDIA_MOVIES}
        target: /media/Movies:ro
        is_directory: true
      - type: bind
        source:  ${MEDIA_SHOWS}
        target: /media/Shows:ro
        is_directory: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl}
      - TZ=${TZ}
    networks:
      - proxy

networks:
  proxy:
    external: true
